//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateLib.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version {0} is available!.
        /// </summary>
        public static string A_new_version_is_available {
            get {
                return ResourceManager.GetString("A_new_version_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 1 day.
        /// </summary>
        public static string After_1_day {
            get {
                return ResourceManager.GetString("After_1_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 10 days.
        /// </summary>
        public static string After_10_days {
            get {
                return ResourceManager.GetString("After_10_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 12 hours.
        /// </summary>
        public static string After_12_hours {
            get {
                return ResourceManager.GetString("After_12_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 2 days.
        /// </summary>
        public static string After_2_days {
            get {
                return ResourceManager.GetString("After_2_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 30 minutes.
        /// </summary>
        public static string After_30_minutes {
            get {
                return ResourceManager.GetString("After_30_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 4 days.
        /// </summary>
        public static string After_4_days {
            get {
                return ResourceManager.GetString("After_4_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 8 days.
        /// </summary>
        public static string After_8_days {
            get {
                return ResourceManager.GetString("After_8_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download updates later?.
        /// </summary>
        public static string Download_updates_later {
            get {
                return ResourceManager.GetString("Download_updates_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should download updates now. This only takes few minutes depending on your internet connection and ensures you have latest version of the application..
        /// </summary>
        public static string Download_updates_now_description {
            get {
                return ResourceManager.GetString("Download_updates_now_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update ....
        /// </summary>
        public static string Downloading_update {
            get {
                return ResourceManager.GetString("Downloading_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, download updates now (recommended).
        /// </summary>
        public static string No_Download_updates_now_recommended {
            get {
                return ResourceManager.GetString("No_Download_updates_now_recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes:.
        /// </summary>
        public static string Release_notes {
            get {
                return ResourceManager.GetString("Release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind later.
        /// </summary>
        public static string Remind_Later {
            get {
                return ResourceManager.GetString("Remind_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me later to update.
        /// </summary>
        public static string Remind_me_later_to_update {
            get {
                return ResourceManager.GetString("Remind_me_later_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string Skip_This_Version {
            get {
                return ResourceManager.GetString("Skip_This_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        public static string Software_update {
            get {
                return ResourceManager.GetString("Software_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is available! You have version {0} installed. Would you download it now?.
        /// </summary>
        public static string Update_is_now_available {
            get {
                return ResourceManager.GetString("Update_is_now_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, please remind me later : .
        /// </summary>
        public static string Yes_Remind_Me_Later {
            get {
                return ResourceManager.GetString("Yes_Remind_Me_Later", resourceCulture);
            }
        }
    }
}
